import type { AnimalPost, User } from './types'

export const currentUser: User = {
  id: '1',
  name: 'Maria Garcia',
  avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
  role: 'volunteer',
  points: 1250,
  level: 5,
  badges: ['first_rescue', 'community_helper', 'weekly_active'],
}

export const mockPosts: AnimalPost[] = [
  {
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop',
    description: 'Perrito encontrado en el Parque Caldas, se ve muy asustado y con signos de desnutricion. Necesita atencion urgente. Por favor, si alguien puede ayudar a rescatarlo.',
    location: 'Parque Caldas, Centro',
    neighborhood: 'Centro Historico',
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    urgencyLevel: 'critical',
    status: 'needs_rescue',
    animalType: 'dog',
    likes: 45,
    comments: 12,
    shares: 8,
    isLiked: false,
    author: {
      name: 'Carlos Mendez',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
      role: 'volunteer',
    },
    recommendations: [
      'Mantener distancia prudente',
      'No alimentar sin supervision veterinaria',
      'Contactar al equipo de rescate',
    ],
  },
  {
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=600&h=400&fit=crop',
    description: 'Max ha completado su tratamiento de desparasitacion. Esta listo para adopcion responsable. Es muy cariñoso y jugueton.',
    location: 'Clinica Veterinaria SnapDog',
    neighborhood: 'La Esmeralda',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    urgencyLevel: 'low',
    status: 'healthy',
    animalType: 'dog',
    animalName: 'Max',
    likes: 89,
    comments: 23,
    shares: 15,
    isLiked: true,
    author: {
      name: 'Dra. Ana Rodriguez',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100&h=100&fit=crop&crop=face',
      role: 'veterinarian',
    },
  },
  {
    id: '3',
    imageUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=600&h=400&fit=crop',
    description: 'Gatita encontrada cerca del Centro Comercial Campanario. Tiene una herida en la pata trasera que necesita atencion veterinaria.',
    location: 'CC Campanario',
    neighborhood: 'La Julita',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    urgencyLevel: 'high',
    status: 'needs_rescue',
    animalType: 'cat',
    likes: 67,
    comments: 18,
    shares: 11,
    isLiked: false,
    author: {
      name: 'Laura Perez',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
      role: 'volunteer',
    },
    recommendations: [
      'Herida visible en pata trasera',
      'Necesita atencion veterinaria urgente',
      'Se encuentra cerca de la entrada principal',
    ],
  },
  {
    id: '4',
    imageUrl: 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=600&h=400&fit=crop',
    description: 'Luna esta en proceso de recuperacion despues de su cirugia. Los veterinarios reportan muy buena evolucion.',
    location: 'Refugio Municipal',
    neighborhood: 'Alfonso Lopez',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    urgencyLevel: 'medium',
    status: 'recovering',
    animalType: 'dog',
    animalName: 'Luna',
    likes: 112,
    comments: 34,
    shares: 22,
    isLiked: true,
    author: {
      name: 'Dr. Pedro Gomez',
      avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100&h=100&fit=crop&crop=face',
      role: 'veterinarian',
    },
  },
  {
    id: '5',
    imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=400&fit=crop',
    description: 'Colonia de gatos en el barrio Bolivar necesita atencion. Se han identificado al menos 8 gatos que requieren esterilizacion.',
    location: 'Calle 5 con Carrera 9',
    neighborhood: 'Bolivar',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    urgencyLevel: 'medium',
    status: 'needs_rescue',
    animalType: 'cat',
    likes: 56,
    comments: 15,
    shares: 9,
    isLiked: false,
    author: {
      name: 'Sofia Ramirez',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
      role: 'volunteer',
    },
    recommendations: [
      'Colonia identificada con 8+ gatos',
      'Necesario programa de esterilizacion',
      'Alimentacion comunitaria activa',
    ],
  },
]
