export type UrgencyLevel = 'critical' | 'high' | 'medium' | 'low'

export type AnimalStatus = 'needs_rescue' | 'in_treatment' | 'recovering' | 'healthy' | 'adopted'

export type AnimalType = 'dog' | 'cat' | 'other'

export interface AnimalPost {
  id: string
  imageUrl: string
  description: string
  location: string
  neighborhood: string
  createdAt: Date
  urgencyLevel: UrgencyLevel
  status: AnimalStatus
  animalType: AnimalType
  animalName?: string
  likes: number
  comments: number
  shares: number
  isLiked: boolean
  coordinates?: {
    lat: number
    lng: number
  }
  author: {
    name: string
    avatar: string
    role: 'volunteer' | 'veterinarian'
  }
  recommendations?: string[]
}

export interface Animal {
  id: string // UID generated by system
  name?: string
  breed: string
  ageEstimated: string
  weight: number
  status: 'sick' | 'treating' | 'recovered'
  registrationDate: Date
}

export interface Medication {
  name: string
  dosage: string
  frequency: string
  duration: string
}

export interface ClinicalRecord {
  id: string
  animalId: string
  date: Date
  veterinarianName: string
  diagnosis: string
  treatment: Medication[]
  notes: string
  attachments?: string[] // URLs to documents/photos
}

export interface User {
  id: string
  name: string
  avatar: string
  role: 'volunteer' | 'veterinarian'
  points: number
  level: number
  badges: string[]
  veterinaryCenter?: string
}
